name: piranha
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - coreutils=9.1
  - mafft
  - minimap2
  - samtools
  - bcftools=1.11
  - tabix=1.11
  - snakemake-minimal

