name: piranha3
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python<3.10
  - coreutils=9.1
  - mafft=7.508
  - minimap2=2.17
  - samtools=1.16.1
  - bcftools=1.11
  - tabix=1.11
  - snakemake-minimal=7.19.1

