name: piranha
on: [push, pull_request]
defaults:
  run:
    shell: bash -l {0}

jobs:
  run_piranha_test:
    name: piranha test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          mamba-version: "1.1.0"
          activate-environment: piranha
          channels: conda-forge,bioconda,defaults
      - name: Install piranha
        run: pip install -e .
      - name: Check piranha version
        run: piranha --version
      - name: Run piranha with test data
        run: piranha -i piranha/test/pak_run/demultiplexed --verbose -b piranha/test/pak_run/barcodes01.csv -t 2 2>&1 | tee piranha.log
      - name: Run piranha with all data
        run: piranha -i piranha/test/pak_run/demultiplexed --verbose -b piranha/test/pak_run/barcodes.csv -t 2 2>&1 | tee piranha_all.log
